# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'reg.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(249, 215)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Logo = QtWidgets.QLabel(self.centralwidget)
        self.Logo.setGeometry(QtCore.QRect(90, 20, 81, 16))
        self.Logo.setObjectName("Logo")
        self.login_input = QtWidgets.QLineEdit(self.centralwidget)
        self.login_input.setGeometry(QtCore.QRect(70, 50, 171, 21))
        self.login_input.setObjectName("login_input")
        self.login_text = QtWidgets.QLabel(self.centralwidget)
        self.login_text.setGeometry(QtCore.QRect(10, 50, 47, 13))
        self.login_text.setObjectName("login_text")
        self.pass_text = QtWidgets.QLabel(self.centralwidget)
        self.pass_text.setGeometry(QtCore.QRect(10, 90, 47, 13))
        self.pass_text.setObjectName("pass_text")
        self.pass_input = QtWidgets.QLineEdit(self.centralwidget)
        self.pass_input.setGeometry(QtCore.QRect(70, 90, 171, 21))
        self.pass_input.setObjectName("pass_input")
        self.buttom_ok = QtWidgets.QPushButton(self.centralwidget)
        self.buttom_ok.setGeometry(QtCore.QRect(30, 140, 75, 23))
        self.buttom_ok.setObjectName("buttom_ok")
        self.buttom_cancel = QtWidgets.QPushButton(self.centralwidget)
        self.buttom_cancel.setGeometry(QtCore.QRect(130, 140, 75, 23))
        self.buttom_cancel.setObjectName("buttom_cancel")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 249, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Авторизация"))
        self.Logo.setText(_translate("MainWindow", "Авторизация"))
        self.login_text.setText(_translate("MainWindow", "Логин"))
        self.pass_text.setText(_translate("MainWindow", "Пароль"))
        self.buttom_ok.setText(_translate("MainWindow", "Ок"))
        self.buttom_cancel.setText(_translate("MainWindow", "Отмена"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
